### ISSUE TITLE
ed25519 privkey length check is failing

### ISSUE THREAD

**Issue by metajack** [coinbase/rosetta-sdk-go#164]
**Describe the bug**

Providing a 64 character hex encoded ed25519 privkey returns this error:
```
Error: unable to to sign payload for 0: invalid privkey length: expected 32 bytes but go 64: unable to sign payloads: unable to create transaction
```

**To Reproduce**

I found this using `rosetta-cli check:construction` with the following address/privkey pair:
address: `1d45c318b5c648fbc5adda931ea82da1`
privkey: `c020f245c55677cefb5259ed3c7b3baee77651acd4171c24985f5bc7bfa99485`

**Expected behavior**

It should accept the key.

**Comment by patrick-ogrady** [comment]
Thanks for posting this @metajack! We will fix this promptly!
