### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/rosetta-sdk-go#237]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/rosetta-sdk-go/compare/a2b3f45c4088357436dc9de1e30068566efa8d8b...33063f8589bb638057503e5e4209144cabb25420) was merged to master by patrick-ogrady.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? No

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-sdk-go&ref=33063f8589bb638057503e5e4209144cabb25420)

**Comment by cindyxkuang** [comment]
👍
