### ISSUE TITLE
MathOperation : Support Multiply / Division Operation

### ISSUE THREAD

**Issue by thanhnguyennguyen** [coinbase/rosetta-sdk-go#239]
**Is your feature request related to a problem? Please describe.**
Calculation on balance need more operations. Now, only **addition** and **subtraction** are supported. It's great to have **multiply** and **division** 

**Describe the solution you'd like**
Support Support Multiply / Division Operation https://github.com/coinbase/rosetta-sdk-go/blob/1e2b4a3d02e14ed747e02fefc9cfabb9e36c3418/constructor/job/types.go#L171

**Comment by patrick-ogrady** [comment]
I think this is a great idea! [As you mentioned](https://community.rosetta-api.org/t/when-rosetta-cli-assign-signature-to-transaction/285/9?u=patrick.ogrady), this would be a great way to limit the % of funds send in a single tx (the most common practice now is some value between 1 and max).
