### ISSUE TITLE
Pass pubKey via prefunded_accounts

### ISSUE THREAD

**Issue by renlulu** [coinbase/rosetta-sdk-go#262]
**Is your feature request related to a problem? Please describe.**

Since our signature algorithm needs sender public key to join the encoding part, so currently I am using `account_identifier`'s `metadata` to let `rosetta-cli` aware of this info and it does work. But this will cause a side effect that we should ensure all `account_identifier` has this metadata, but that cannot happen in the confirmed transaction as it just doesn't contain it. That means I cannot make `derive api` contain `pubKey` too. So I would like to ask if there is another way to pass `pubKey` else in the json file.

```
 "prefunded_accounts": [
   {
    "privkey": "******",
    "account_identifier": {
     "address": "c18273C95DE42Eb979E99f8842aA0cF7343Cb42e",
     "metadata": {
      "pubKey": "03ac3d6f2fed0102253d7658de77d802ec6cd6d8f5bdd056ae342540be3d00ae3f"
     }
    },
    "curve_type": "secp256k1",
    "currency": {
       "symbol":"ZIL",
       "decimals":12
    }
   }
  ]
```

**Comment by patrick-ogrady** [comment]
> Since our signature algorithm needs sender public key to join the encoding part, so currently I am using account_identifier's metadata to let rosetta-cli aware of this info and it does work.

Can you not derive the `pubKey` from the provided `privKey`?

We already added a change to the specification that allows an implementation to request the `pubKeys` of specific `AccountIdentifiers` during construction. Are you using it (if so, what is missing)?:
* https://github.com/coinbase/rosetta-specifications/pull/45
* https://github.com/coinbase/rosetta-specifications/pull/46

The `rosetta-cli` fully supports this btw ^^^

**Comment by renlulu** [comment]
Oh I am not using it. Yes, I can drive the `pubKey` from the `privKey`. I was researching a way to get the private key from config but could not though. Will take a look at your PRs. Thanks!

**Comment by patrick-ogrady** [comment]
Closing this for now...happy to answer any other questions!

**Comment by renlulu** [comment]
OH! it works, thanks a lot.

**Comment by patrick-ogrady** [comment]
Very cool!
