### ISSUE TITLE
Shouldn't MaxTableSize be 4x ValueLogFileSize?

### ISSUE THREAD

**Issue by sidhujag** [coinbase/rosetta-sdk-go#268]
I saw #267 increased the table size, but it did not keep the ratio of 400% consistent. Is this OK?

According to your [notes](https://github.com/coinbase/rosetta-sdk-go/blob/master/storage/database/badger_database.go#L108):

"we configure MaxTableSize to be 4 times the size of ValueLogFileSize (if we skewed any further to MaxTableSize, we would quickly hit the default open file limit on many OSes)."

**Comment by patrick-ogrady** [comment]
Great question, @sidhujag!

There is no restriction on the ratio of `MaxTableSize` to `ValueLogFileSize`. I made this note when trying to restrict `rosetta-bitcoin` memory usage to a constant amount without too significantly impairing our ability to create large database transactions. To be honest, this may now be outdated now that we are using `mmap` files.

This performance setting is only activated when `memory_limit_disabled` in `rosetta-cli` so we don't have the same concerns about ensuring we have reasonable memory usage.

**Comment by sidhujag** [comment]
thanks!
