### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/rosetta-sdk-go#3]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/rosetta-sdk-go/compare/dafa60f2a02ee6fe2a680edb3664ad874cfd4052...80c1e05e15b242f492483118c2e93aeac4f655ce) was merged to master by patrick-ogrady.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-sdk-go&ref=80c1e05e15b242f492483118c2e93aeac4f655ce)

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-sdk-go&ref=e0ac42f8525e1f85648ad3c3b901274f2921c256)

**Comment by patrick-ogrady** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for patrick-ogrady @ 2020-04-03 00:27:31 UTC
User cannot review their own pull request

**Comment by etscrivner** [comment]
:+1:

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
etscrivner | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-sdk-go&ref=e0ac42f8525e1f85648ad3c3b901274f2921c256)
