### ISSUE TITLE
Rosetta Constructor DSL: error parsing a string containing a "-" character

### ISSUE THREAD

**Issue by rufsam** [coinbase/rosetta-sdk-go#351]
**Describe the bug**

Hi! When using the Rosetta Constructor DSL for example following way:

```
create_account(1){
  create{
    network = {"network":"chrysalis-devnet", "blockchain":"iota"};
    key = generate_key({"curve_type": "edwards25519"});
    account = derive({
      "network_identifier": {{network}},
      "public_key": {{key.public_key}}
    });

   ...
   
  }
}
```

the Rosetta Construction API check fails. The `-` between `"chrysalis-devnet"` looks like a subtraction for the parser.

Is there a way around this issue? Can I encode the  `-` somehow?

**To Reproduce**

1) setup a *.ros file for the Construction API check
2) choose a network name that contains a `-`
3) start the Construction API check

**Expected behavior**

I expect that the network name is allowed to contain a `-` char.

Many thanks for the help.

**Comment by shrimalmadhur** [comment]
Please follow the solution suggested in https://github.com/coinbase/rosetta-cli/issues/248 
Will work on fixing the native parsing.
