### ISSUE TITLE
Make the Logger an optional middleware in routers

### ISSUE THREAD

**Issue by matheusd** [coinbase/rosetta-sdk-go#59]
**Is your feature request related to a problem? Please describe.**
Using the current router mux exported by the server package results in endpoints always logging accesses in a specific format. When running a Rosetta server implementation backed by some other pre-existing node server that logs in a different format, logs become slightly harder to read.

Additionally, we might want to offer different forms of logging or offer the option to disable logging altogether to users. 

**Describe the solution you'd like**
Make middlewares (including the currently existing Logger) configurable when calling `server.NewRouter`.

**Describe alternatives you've considered**
Another alternative would be disabling logging altogether in the library and having that be a responsibility of users.

**Comment by patrick-ogrady** [comment]
This has been a common request among a few users of `rosetta-sdk-go` @matheusd. I've added this to the `v0.4.0` release milestone.

Let me know if you'd like to take a stab at working on this!

**Comment by matheusd** [comment]
After taking a second look at the routers, I believe the easiest solution would be to simply drop the existing Cors and Logger middleware from the `NewRouter()` call and leave it up to the caller to install any middleware they desire. They can be offered as package-level clients and we could add an example on how to use them.

If we really want to offer the ability to add a per-route middleware (such as the current router) the simplest change would be to switch the signature of `NewRouter` to something like:

```go
type Middleware func (http.Handler, name string)
func NewRouter(middlewares []Middleware, routers ...Route) http.Handler {
...
}
```

Do either of those seem acceptable?

**Comment by patrick-ogrady** [comment]
@matheusd Thanks for digging into this! I like the idea of leaving it up to the caller to install any middleware they desire. I think the "logger per route" strategy was the default for the codegen but I don't feel any particular allegiance to it. You could easily accomplish something similar in a custom logger by inspecting the `http.Request` on the `HandlerFunc`.

I think having some simple default logger that can be added still makes sense but agree the current one is AWFUL!

This code is all generated, so any changes will need to occur here: https://github.com/coinbase/rosetta-sdk-go/blob/master/templates/server/routers.mustache
