### ISSUE TITLE
[Fetcher] Allow for insecure HTTPS for debugging

### ISSUE THREAD

**Issue by LindaOrtega** [coinbase/rosetta-sdk-go#61]
**Is your feature request related to a problem? Please describe.**
Our node endpoints uses HTTPS for our rosetta endpoints. In production we have valid domain names and valid certificates, but when debugging we use self-signed certificates. The validator would throw an error when running a node with a self-signed certificate during testing/debugging.

**Describe the solution you'd like**
Add a flag that allows for insecure HTTPS connections when debugging.

**Describe alternatives you've considered**
Maintained a fork of this repo that allows for insecure connection.
We're also working on having a "local" setting for the rosetta endpoints.

**Additional context**
This is a screenshot of the changes I made to a fork of this repo to allow for insecure HTTPS.
<img width="1651" alt="Screen Shot 2020-07-08 at 3 54 40 PM" src="https://user-images.githubusercontent.com/10335533/86964054-79d95300-c133-11ea-88fd-7a52ff4c5bee.png">

**Comment by patrick-ogrady** [comment]
Thanks for posting the issue @LindaOrtega! This should be a pretty easy option to add and will work this in for the next release.
