### ISSUE TITLE
Need some clarification on Specifications 

### ISSUE THREAD

**Issue by sambacha** [coinbase/rosetta-sdk-go#82]
**Is your feature request related to a problem? Please describe.**
[see this](#spec)

**Describe the solution you'd like**

Please provide guidance on the issues I have submitted here: https://github.com/coinbase/rosetta-specifications/issues/23

**Describe alternatives you've considered**

[Stop all development on this "rosetta" thing](https://github.com/freight-trust/rosetta-rpc) 
**Additional context**

I have a few questions/requests for clarification as to your specification 

[](#spec)
## Amount.yaml

Amount is described as:

`  Amount is some Value of a Currency`

Can it be changed to:

`  Amount is some Unit of Account`

**currency** has *legal* implications, and strictly speaking, this is not entirely accurate for EVM chains as *gas* is the unit of account for EVM chains (typically) whereas ethereum 

## Account Identifier 

currently reads:
- The account_identifier uniquely identifies an account within a network.

can it be expanded to fit a more approximate meaning of the word? As you can have a chain that uses the same derivation path in both instances but have assets in different addresses.

Also, can this be explicit in what it means as to what constitutes an "account"? Is it only EOA - Externally owned accounts only or can smart contract addresses be included with no distinction?

**informative ref**: [eip1191](https://eips.ethereum.org/EIPS/eip-1191). 

example:
```javascript
const hexChecksumChain = (name: string, coinType: number, chainId?: number) => ({
  coinType,	  coinType,
  decoder: decodeChecksummedHex,	  decoder: makeChecksummedHexDecoder(chainId),
  encoder: encodeChecksummedHex,	  encoder: makeChecksummedHexEncoder(chainId),
  name,	  name,
});	});
```
*example ref*: [ensdomains/address-encoder/commit/5bf53b13fa014646ea28c9e5f937361dc9b40590](https://github.com/ensdomains/address-encoder/commit/5bf53b13fa014646ea28c9e5f937361dc9b40590#diff-f41e9d04a45c83f3b6f6e630f10117feR186)

### Network Identifer.yaml
  
  The network_identifier specifies which network a particular object is associated with.

"If a blockchain has a specific chain-id or network identifier, it
      should go in this field."
      
Can we also provide an (optional) direct link to a repository containing the genesis file? This would be the least ambiguous as to 
** Informative ** [ethereum-listss/chains](https://github.com/ethereum-lists/chains)
 
Additional references and sources can be made available. A Java SDK would be trivial, I just would like to not have to make awkward choices if possible, these are the ones just most apparent. 

Thank you.

**Comment by patrick-ogrady** [comment]
Sorry for the delay in responding here @sambacha : https://github.com/coinbase/rosetta-specifications/issues/23#issuecomment-663730386

Closing the issue on this repo as it is better suited for `rosetta-specifications`.
