### ISSUE TITLE
[Fetcher] Assumes genesis block the same across Sub-Networks

### ISSUE THREAD

**Issue by LindaOrtega** [coinbase/rosetta-sdk-go#96]
**Describe the bug**
The Fetcher's asserter initialization function does not have an option to specify a target sub-network. Consequently, it assumes that the first network it sees is the `primaryNetwork`. See the following line for details:
https://github.com/coinbase/rosetta-sdk-go/blob/73d638d69870d85a0329ea396545553450171795/fetcher/fetcher.go#L143

As a result of this, I saw the following error when running the `rosetta-cli check:data` command on a sub-network.
```
2020/08/05 18:46:28 block 332604 fetch error: BlockIdentifier.Hash == ParentBlockIdentifier.Hash
2020/08/05 18:46:28 retrying fetch for block 332604 after 0.697379s
```
Below are the lines that seem to be throwing this error: 
https://github.com/coinbase/rosetta-sdk-go/blob/73d638d69870d85a0329ea396545553450171795/asserter/block.go#L379-L381

This scenario was triggered because the sub-network in question does not have a genesis block with a block height of `0`.  Its genesis block occurs at block height `332604` (the block height throwing the error), but the genesis block of the zeroth sub-network (the sub-network used to initialize the asserter) has a block height of `0`. The check of whether block `332604` is the genesis block therefore fails and the asserter erroneously expects that the parent hash of block `332604` be different from its block hash.

**To Reproduce**
Have a blockchain that returns two sub-networks for `network/list`.
For the first sub-network, have `/network/status` return a genesis block identifier with `block height=0`. For example,
```
{
  "hash": "r21zg8E011awAbEghzNBOI4RtKUZ-wHLkUwio-5dKpE",
  "index": 0
}
```
For the second sub-network, have `/network/status` return a genesis block identifier with a non-zero block height. For example,
```
{
  "hash": "VsDfA3fyhpKdPR-KWzBARmh5htuBLnQe7ZXcLIphSaw",
  "index": 332604
}
```
Then run `rosetta-cli check:data` on the second sub-network.

**Expected behavior**
When testing sub-network `X`, populate the Asserter's `genesisBlock` field with sub-network `X`'s genesis block. 

**Additional context**
Ran `rosetta-cli` version `v0.4.0`.
Ran `rosetta-sdk-go` version `v0.3.3`.

After some debugging modifications, I noticed the following behavior in `rosetta-cli`:
- For sub-network 0 (no error thrown, `genesis block height=0`, correct genesis block in Asserter):
```
asserter: genesis block: index: 0
asserter: genesis block: hash: r21zg8E011awAbEghzNBOI4RtKUZ-wHLkUwio-5dKpE
data tester: genesis block: index: 0
data tester: genesis block: hash: r21zg8E011awAbEghzNBOI4RtKUZ-wHLkUwio-5dKpE
Initialized reconciler with 0 previously seen accounts
2020/08/12 17:34:07 Syncing 0-999
2020/08/12 17:34:08 Syncing 1000-1999
2020/08/12 17:34:09 Syncing 2000-2999
2020/08/12 17:34:09 Syncing 3000-3999
```
- For sub-network 18 (the one that threw the error):
```
asserter: genesis block: index: 0
asserter: genesis block: hash: r21zg8E011awAbEghzNBOI4RtKUZ-wHLkUwio-5dKpE
data tester: genesis block: index: 332604
data tester: genesis block: hash: VsDfA3fyhpKdPR-KWzBARmh5htuBLnQe7ZXcLIphSaw
Initialized reconciler with 0 previously seen accounts
2020/08/12 13:57:12 Syncing 332604-333603
2020/08/12 13:57:12 block 332604 fetch error: BlockIdentifier.Hash == ParentBlockIdentifier.Hash
2020/08/12 13:57:12 retrying fetch for block 332604 after 0.477209s
2020/08/12 13:57:13 block 332604 fetch error: BlockIdentifier.Hash == ParentBlockIdentifier.Hash
2020/08/12 13:57:13 retrying fetch for block 332604 after 0.612566s
```
- For sub-network 5 (no error thrown since its `genesis block height=0` but incorrect genesis block in Asserter):
```
asserter: genesis block: index: 0
asserter: genesis block: hash: r21zg8E011awAbEghzNBOI4RtKUZ-wHLkUwio-5dKpE
data tester: genesis block: index: 0
data tester: genesis block: hash: wXSuR_3WBkrdEV4proOm1YS4pBiX4uZI_KrNQfr24ls
Initialized reconciler with 0 previously seen accounts
2020/08/12 13:58:47 Syncing 0-999
2020/08/12 13:58:48 Syncing 1000-1999
2020/08/12 13:58:48 Syncing 2000-2999
```

**Comment by patrick-ogrady** [comment]
Nice find @LindaOrtega! We will prioritize a fix for this ASAP!
